bootstrap/cleanup.go
context.go
module_ctx.go
parser/parser.go
parser/parser_test.go
parser/printer.go
parser/printer_test.go

Adds some new features to Blueprint, including += assignments and + operator on maps

New features

---

context.go
parser/parser.go
parser/parser_test.go
parser/printer.go
parser/printer_test.go

Two patches to fix bpfmt issues, one fixes some whitespace and comment printing issues, the other fixes parsing a Blueprints file for formatting when it references variables from parent Blueprints files.

bpfmt fixes

---

ninja_strings.go
ninja_strings_test.go

Fixes a bug in parseNinjaString and adds tests for it.

Fix bug in parseNinjaString

---

bootstrap/command.go
ninja_strings.go
ninja_strings_test.go
ninja_writer.go
pathtools/lists.go

These patches improve performance in Blueprint.  Most are minor gains, but the last one massively improves performance by enabling parallelism.  The early ones are still worth applying, they mostly help with writing out the final ninja file which is not parallelized.

Performance improvements

---

proptools/proptools.go

Modules that want properties that vary by variant often need to create
zeroed copies of property structs.  Add CloneEmptyProperties to proptools
that is the equivalent of calling CloneProperties and then ZeroProperties,
but is much faster because it directly creates zeroed objects.
Saves 200ms in Context.ParseBlueprintsFiles and Context.ResolveDependencies
in one case, which will be valuble when we start parsing Blueprints files
for cases where we are not regenerating the manifest, for example when
generating documentation or doing context-aware bpfmt.
Change-Id: I3d4a6af2f393886d95f27d15afc1a455d8dd5fc6

Add proptools.CloneEmptyProperties

---

module_ctx.go

Change-Id: I6cc0afae699cf03f84a70e5582cf554642bbd481

Add CreateLocalVariations to BottupUpMutatorContext.

---

unpack.go
unpack_test.go

Allow tagging a nested property structure with
`blueprint:"filter(key:\"value\")"`, which will only allow property
assignments to properites in the nested structure that are tagged
with `key:"value"`.  Moving the filter into Blueprint instead of
the project build logic allows more reliable and consistent error
messages.
Change-Id: I06bc673dde647776fc5552673bdc0cdcd7216462

Support filtering nested structures by tag

---

bootstrap/bootstrap.go

This is for stageMain and prevents build.ninja.in from being
accidentally deleted.
Change-Id: I9675874c61c3db0bf34c47498968623b8c183e95

bootstrap: Added phony rule for bootstrapManifest.

---

context.go

Replaced map with list so that singletons will execute in the order
that they were listed.
Change-Id: I62919b14110b2b6f1f31c18f249ca64b85898ab1

context: Changed singletons to execute in order.

---

context.go
parser/parser.go

The Go race detector found a race condition in the parser, which
highlighted a few related bugs. A variable could be defined but
not referenced in a Blueprints file, then appended to in multiple
subdirs= Blueprints files.  The race detector caught the multiple
writes to assignment.Referenced from the parsers for the subdirs
Blueprints files, but multiple appends would be much more serious.
To fix this, keep local and inherited variables separate in the
Scope object and export that info to the parser.  Disallow
appending to non-local variables, which was already the intended
behavior.  Only update the referenced boolean for local variables.
Together, this should prevent all writes to Assignment objects
from parsers other than the one that created them.
Also improves the error handling code …

Fix bugs related to local vs. inherited variables

---

ninja_defs.go
ninja_writer.go
ninja_writer_test.go

Support comments in build rules.

---

build.ninja.in
ninja_defs.go

bash$ sh tests/test.sh
passes now. Thanks.

Add blank line after build rules, for human readability.

---

context.go

When building a subset of a source tree, some of the subdirectories
mentioned in the subdirs variable may be missing.  Add support for an
optional_subdirs variable, which won't error out if the requested
directory is missing.

Add optional_subdirs variable support

---

context.go
package_ctx.go

Soong needs to add dependencies during a VariableFunc. (we're doing a glob)

Add AddNinjaFileDeps to PackageContext

---

bootstrap/command.go
context.go
module_ctx.go
singleton_ctx.go
splice_modules_test.go

Colorize errors and catch panics to produce more useful errors.

Improve error handling

---

proptools/extend.go
proptools/extend_test.go

ExtendProperties is the same as AppendProperties or PrependProperties,
but takes a function that determines whether each property should be
appended or prepended.
Change-Id: I26e400d56d75a88bab9c27c382ee5321bc623ee5

Support ExtendProperties that can append or prepend

---

bpmodify/bpmodify.go
context.go
parser/ast.go
parser/parser.go
parser/parser_test.go
parser/printer.go
parser/printer_test.go
parser/sort.go
unpack.go

Make a few more refactoring changes to blueprint/parser to prepare for utilities to modify an AST.

More parser cleanups

---

unpack.go

unpackProperties was instantiating all nil struct pointers in any struct
that had a property set.  Check if the property is set first, and only
instantiate the struct if it was set.
This has a slight behavioral change, as now structures that only exist
through nil pointers and are never set into will not be type-checked.
This should be fixed in a later patch set that moves the type checking
to be done across all property structs once per factory before blueprint
files are loaded.
Change-Id: I0dea34d7fff76bb4fc907516a2d996e4ea2408d6

Only instantiate nil struct pointers that are used

---

context.go

runMutators was sending the wrong value into errsCh, hiding all errors.
parallelVisit had a data race on error, send the cancel signal over a
channel instead of writing to a bool from a goroutine.
Change-Id: I18919d71464c094db5846badbfac80f99366d70c

Fix error reporting in parallel mutators

---

context.go

Convert parallelVisitAllBottomUp into a generic parallelVisit that takes
a visitOrderer to select top down or bottom up.  Combine
runTopDownMutator and runBottomUpMutator into runMutators that takes a
mutatorDirection to select the visitOrderer for parallelVisit and which
function pointer in the mutatorInfo to run.  Optimize out the
updateDependencies to only run if dependencies have been modified to
avoid running it after TopDownMutators that cannot modify dependencies.
Change-Id: Ib00302db1108ebab2ce8e01b20aa026140d382a4

Parallelize TopDownMutators

---

bootstrap/command.go
context.go
module_ctx.go
unpack.go
unpack_test.go

Report module name and variant and property names in errors.
Change-Id: I747f840402497b2c92bf8c565d7c50af33e6ab0e

Improve error reporting

---

.travis.install-ninja.sh
bootstrap/bootstrap.go
build.ninja.in
context.go
ninja_defs.go
ninja_writer.go
ninja_writer_test.go

Added in Ninja 1.7, for outputs that will not show up in $out.
(Also upgrades travis to ninja 1.7.1)

Support implicit outputs

---

ninja_defs.go

Ninja supports deps and depfile properties specified on build
statements, allow them to be specified in BuildParams.
Change-Id: I46eac5571350426f1419908def21f7d042f8739a

Support deps and depfile properties on build statements

---

context.go
module_ctx.go

Mutator context goroutines appending directly to the global Context's
replacements list causes a data race.  Send them over a channel
instead.
The renames and replacements are local to the mutator, so move them
out of Context and into the runMutator method.
Change-Id: I797edb1e27ee29f8946c58101b40fcfb50a32eb9

Fix data race when applying replacements

---

module_ctx.go

Instead of forcing every mutator or module to use VisitDirectDeps
to iterate through its deps, allow it to request a dependency by
name to return the Module.
Change-Id: I18b23bffa324bb9d93a7743b6e2a19c07058c775

Add ModuleContext method to get dependency by name

---

bootstrap/bootstrap.go

In order to use certain syscalls, some source must only be compiled on one of darwin or linux. There are also cases where it's simplest to have two implementations of a method (or struct) instead of choosing an implementation at runtime.
The standard go tools use _<GOOS>.go for this, but the explicit structs map better into the current blueprint format (and you can still use _darwin.go / _linux.go to maintain compatiblity with those tools).
Test: Define _linux.go / _darwin.go files, ensure only one is compiled.

Support filtering OS-dependent go files using _darwin/_linux.go

---

context.go

Context already has VisitDepsDepthFirst[If], add VisitDirectDeps[If].
Change-Id: Id550bc14275db230c19fd6ca14b67b305dd7d96b

Add Context.VisitDirectDeps

---

context.go

Darwin has a default limit of 256 open files per process.  Parsing
too many blueprint files in parallel can hit the limit.  Cap the
concurrency at 200.
Test: manual testing with limit set to 32
Change-Id: Ic64d21d2c0ffd7c86bf3f02fb51216ee5684a80c

Cap concurrency when parsing blueprint files

---

parser/ast.go

Change-Id: If53f696fbe937e007b902434f62d0d92435846dd

Some util functions to support bpfix

---

gotestmain/gotestmain.go

Use testing.MainStart to support test packages that implement
TestMain for initial setup and teardown.
Change-Id: I7330a8e922448063f291f7b5b2eed31d274248bd

Support TestMain in tests

---

Blueprints
microfactory/main/main.go
microfactory/microfactory.bash
microfactory/microfactory.go
microfactory/microfactory_test.go

This set of changes exposes a "github.com/google/blueprint/microfactory" package, with a refactored interface that's more usable from other tools.

Export microfactory as a package

---

bootstrap/bootstrap.go

In case the primary builder wants to depend on a go binary by name, expose an interface to find the real installed path of the binary.
Most of this change is changing it so that we're storing the install path without any ninja references.

Expose the installed path for Go binaries

---

parser/printer.go

Bug: 62957047
Test: m -j
Change-Id: I50d61d2c4a15af571d3bd5ca95f8ff7e3f18c382

Utils to support removing duplicate shared_libs

---

microfactory/microfactory.go

This is necessary to support other go code that uses build tags to control which files build on which platforms. For example, the github.com/golang/protobuf/proto package includes two implementations of pointer:
pointer_reflect:
```go
// ...
// +build appengine js
// This file contains an implementation of proto field accesses using package reflect.
// It is slower than the code in pointer_unsafe.go but it avoids package unsafe and can
// be used on App Engine.
```
pointer_unsafe.go:
```go
// ...
// +build !appengine,!js
// This file contains the implementation of the proto field accesses using package unsafe.
```
Without this change, microfactory tries to include both files, which breaks, since that enables multiple implementations of the same symbols. This implements the logic to find …

Make microfactory support go build tags

---

context.go

Bug: 65683273
Test: m -j nothing # which runs unit tests
Change-Id: I00862cd9673719424a2b18e347c7f9fe84be2857

Support files named Android.bp in tests

---

context.go
context_test.go
module_ctx.go
name_interface.go
ninja_strings.go

Bug: 65683273
Test: m -j nothing # which runs unit tests
Change-Id: I850e78ebcdbee68637f66d81fc127f19dd28508a

Have handleOneFile(child) wait for handleOneFile(parent).

---

glob.go

Glob names were appending every excluded file, which could result
in too many / characters for ninja to handle.  Use a hash if the
result contains too many / characters.
Change-Id: I88920f0596df49639a6c2b4f8af47ea8fdc1ee5a

Limit length of glob result file names

---

bootstrap/bpglob/bpglob.go
bpfmt/bpfmt.go
bpmodify/bpmodify.go
microfactory/microfactory_test.go

Change-Id: I5135e0daecd20abce9a66631f5f55230168613de

Fix format issues found by go vet

---

Blueprints
parser/ast.go
parser/modify.go
parser/modify_test.go
parser/parser.go
parser/parser_test.go

Patch and PatchList provide an API for making changes to substrings
of a Blueprint file by parsing the AST and using the token positions
to perform text replacements.

Add Patch and PatchList for making textual changes

---

proptools/proptools.go

I get the logic wrong every time I try to make a *bool property
that defaults to true.
Change-Id: Idc409921c3a4baecf611acf348176f261712cb92

Add proptools.BoolDefault and proptools.StringDefault

---

context.go

Running with the data race detector enabled hits a 8192 active
goroutine limit.  Reduce the maximum number of active goroutines
by limiting parallelVisit to 1000 goroutines.  Also rewrite
cloneModule in terms of parallelVisit.
Change-Id: Icdd63648e8e010557b624e12592156490b40adb9

Reduce maximum goroutine count

---

bootstrap/bootstrap.go

Linking tests needs the same dependencies that linking binaries
got in https://github.com/google/blueprint/pull/222.
Change-Id: I33330f3184b8c0fd2bc20b48736c20d6edeaea68

Add missing dependencies when linking tests

---

gotestmain/gotestmain.go

go test supports running examples as tests and verifying their
output, add support for running them to gotestmain.
Change-Id: If51abc64467d4701195cefc6db513f4d008794b5

Support examples as tests

---

module_ctx.go

Add OtherModuleDir, OtherModuleSubDir, and OtherModuleType to
ModuleContext and TopDownMutatorContext, and add ModuleType to
BaseModuleContext.
Change-Id: If5c873a2620ef10333c0bdba5ab89d4256e5fdf2

Add more OtherModule* methods

---

doc.go

The previous link seems to be outdated.

Fix Ninja build system site link

---

proptools/extend.go

Test: N/A
Change-Id: Id95afbea7fbccddafb9f2f0e068967d5547cc469

Fix/improve comments on prepending/appending props

---

context.go

This fixes a bug that reverse dependency can't be made for modules
having local variations. Previously, when module A having local variants
calls AddReverseDependency to module B having local variants, the match
is tested between the non-local variants of module A against all
variants of module B, which can never be successful.
This change fixes it by using all variants of module A when
findMatchingVariants is called for AddReverseDependency.
Test: m
Change-Id: Ib289188a5dd58c72bd6ba07e3c0f825f8b1c6b1b

Don't ignore local variations when creating reverse dep

---

go.mod
proptools/proptools.go

Add proptools.Int and proptools.IntDefault that behave analogously
to proptools.String and proptools.StringDefault.
Change-Id: I41fd3417c973c9ff4a5aa6680546b4b893784745

Add proptools.Int and proptools.IntDefault

---

module_ctx.go

Allow mutators to modify properties of the newly created module
by returning it.
Change-Id: Ia1acc70b6196195d1bad58c88ab3def70b99e42c

Make CreateModule return the newly created module

---

bootstrap/bootstrap.go

Don't write to $buildDir/.bootstrap in the ninja file generated for
the main stage.
Test: examine main stage build.ninja file
Change-Id: I9c6183c9a434ff11d44cdd4f9844eae192ebfe03

Move outputs of bootstrap modules in main stage to separate directory

---

bootstrap/bootstrap.go
bootstrap/cleanup.go
bootstrap/command.go
bootstrap/config.go
context.go
pathtools/fs.go
pathtools/fs_test.go

Bug: 146437378
Test: pathtools/fs_test.go
Change-Id: I513ceb9b8b0b4f18223bc34ecad9846fe220709b

Allow primary builder to change working directory

---

pathtools/fs.go
pathtools/fs_test.go

OsFs may be asked to read absolute paths if buildDir is absolute.
Check if the path is absolute before prepending srcDir to it.
Bug: 146437378
Test: fs_test.go
Change-Id: I2a67593e9d836ca3e11dc10b81f49a4fb49d2cdf

Fix reading absolute paths through OsFs

---

parser/ast.go
parser/parser.go
parser/parser_test.go
parser/printer_test.go
parser/sort.go
proptools/extend_test.go
proptools/proptools.go
proptools/unpack.go
proptools/unpack_test.go

Allow property value to be a list of maps, e.g.
my_module {
my_list: [
{ name: "foo", value: 42, something: true, },
{ name: "bar", value: 34, something: false, },
],
}
Test: internal
Change-Id: I2fc37d692aac39f23c9aa7bda2859ab49f3bc672

Implement list of maps

---

context.go
module_ctx.go

This allows guarding calls to AddVariationDependencies and
AddReverseDependency to register dependencies on optional modules.

Add ctx.OtherModule(Reverse)DependencyVariantExists.

---

bootstrap/glob.go

This makes a minimal difference on my AOSP tree (which is on a fast NVME
drive), but it saves ~10-15% of the time in our primary builder
(soong_build) on larger trees on slower drives.
We're always going to run the glob tool at least once outside of the
primary builder, and ninja only loads depfiles created after running the
tool, so this should be a no-op change.
We still need to write the list file (if it has changed), since that's
the file we're adding as a dependency of the primary builder, so the
effective timestamp must be earlier than the build.ninja timestamp.

Stop writing depfiles from Glob singleton

---

context.go
module_ctx.go

Adds support for making the replacement of one dependency with another
conditional on the from and to module as well as the tag used.

Add ReplaceDependeciesIf to allow for conditional replacement

---

bootstrap/bpdoc/bpdoc.go
bootstrap/bpdoc/bpdoc_test.go
bootstrap/bpdoc/properties.go
bootstrap/bpdoc/reader_test.go

Test: m soong_docs
Test: go bpdoc tests
Change-Id: I99f15405e1a7d4a819f6fb20fda22372afe253e1

Add docs for nested and embedded structs

---

CODEOWNERS

Add CODEOWNERS: @google/blueprint

---

bootstrap/bpdoc/bpdoc_test.go
bootstrap/bpdoc/properties.go
bootstrap/bpdoc/reader_test.go

Test: go test bpdoc tests
Test: m soong_docs
Change-Id: I6a4a916e1f72b3fc702da90c32a2eddca70b3bac

Identify the type of the list for bpdocs

---

module_ctx.go

In the coordination between #316 and #318 the calls to mctx.pause()
were forgotten, causing dependencies returned by the Add*Dependency
calls to be in an undefined state.  Add the missing calls to
mctx.pause().
Change-Id: I648ad269449777363801785059b13b866424d4b5

Actually pause mutators when adding dependencies

---

pathtools/fs.go
pathtools/glob.go

Use the info.IsDir() shortcut.
Change-Id: Ibba8bbc6af295e3d86321b0c070a84c2b7008dd9

Use info.IsDir() instead of info.Mode()&os.ModeDir != 0

---

context.go

Avoid reallocating module.forwardDeps and module.reverseDeps every
time through updateDependencies by resetting the slices without
reducing their capacity.  Accumulate dependencies to visit directly
into module.forwardDeps.  Use a loop instead of a map to check
for duplicates, average number of dependencies is measured to be
9.5, although there are a few outliers with up to 2108.
Reduces mean soong_build execution time on internal master from 87s
to 82.7s (5%).
Test: context_test.go
Change-Id: I58fcd5514e494bafa965443461851b21b7bce382

Optimize updateDependencies

---

context.go
context_test.go

Fix detecting cycles in parallelVisit when the first alphabetical
module is not part of the cycle, but depends on the cycle.  Instead of
starting from the first alphabetical module, check every module in a
determinsitic order and return the first time a cycle is found.
Test: Test_parallelVisit
Change-Id: I03726f838ec42975251088ba75158103940115c2

Fix detecting cycles in parallelVisit
