context.go
splice_modules_test.go

spliceModules was carefully reallocating the slice if necessary, and
then throwing away the reallocated slice and writing to the too-short
original slice.  Fix the bug, and add tests that would have caught it.
Change-Id: Ifc13b2025198b270c97097fd7d28cd36e460c98c

Fix a bug in spliceModules and add tests

---

context.go

createVariations relies on reusing the logicModule for the first
variant in order to replace the original module in the global module
map, which prevents leaving old split modules around in the global
module map.  Add comments to explain the behavior.
Change-Id: Ia06d7fa4bc777e807241996d4e8bf977e641d741

Document subtle behavior in createVariations

---

context.go

Calling CreateVariations with no variants will corrupt the
modules list with a module with nil logicModule, panic early
with a useful message instead.
Change-Id: Ic5c921efcba70c54efb5bb21a9626b2999376a69

Add error checking for calling CreateVariations with no variants

---

context.go

The patch "Fix panic when dependency cycle includes the first
module visited" caused cycles to print incorrectly by initializing
the current module to be the last module in the cycle, when it
should be the first module in the cycle.
Change-Id: Iaf939283a48faa4cc6eeb9b19aed57993575a687

Fix cycle printing

---

doc.go

This fixes the Godoc HTML rendering, swapping this:
for this:

Indent code block in doc.go

---

live_tracker.go
package_ctx.go
scope.go

This implements the Pool interface. An instance of a builtinPool
is created for the Console pool.
Change-Id: I03334c25495dc573aef2c0e62415352a0b10d6fd

Adding a builtinPool type

---

bootstrap/command.go
ninja_strings.go
ninja_strings_test.go
package_ctx.go
pathtools/glob.go
pathtools/glob_test.go

This patch set fixes a bug in pathtools.Glob that caused it to miss some directory dependencies, and adds support for recursive globs using "**", and GlobWithExcludes.

pathtools.Glob bugfixes and features

---

context.go
module_ctx.go

AddVariationDependencies is used to add dependency modules that
have the same variations as the depending module, but with additional
variataions.  It cannot be used to add a dependency that is unrelated
to the depending module, for example a dependency on a code generator
that needs to run on the host to generate a target source file.
Add AddFarVariationDependencies, which adds a dependency on a module
that contains all the passed variations, but ignores the variations
of the depending module, as well as any unspecified variations on
the dependency module.
Change-Id: Ief696ec85cf33ad5fb187227d215c1c2e894f962

Add support for "far dependencies"

---

context.go

Don't put nil to c.moduleNinjaNames[ninjaName].
Change-Id: I393c584931b702e63663e14263d365582abe8ce7

Fix insertion to Context.moduleNinjaNames

---

pathtools/glob.go
pathtools/glob_test.go

If the initial non-wild part of a glob path does not exist, return
the last existing part of the path as a dependency to detect if the
path is created later.
Change-Id: Ib5a39e6830cb386deed26e017279d0aac1bc9a20

Fix glob dependencies when initial non-wild path does not exist

---

Blueprints
bootstrap.bash
bootstrap/bootstrap.go
bootstrap/cleanup.go
bootstrap/command.go
bootstrap/config.go
build.ninja.in
gotestmain/gotestmain.go

Users that want to enable this option can use the '-t' option to
bootstrap.bash when passing '-r'. Builders that want to enable this can
set RUN_TESTS="-t" in their bootstrap.bash.
The gotestmain tools is needed to write the main functions for the test
binaries, since 'go test' doesn't work well in this environment.

Add option to build and run tests during bootstrap

---

Blueprints
bootstrap/bootstrap.go
bootstrap/bpdoc/bpdoc.go
bootstrap/command.go
bootstrap/writedocs.go
build.ninja.in
context.go
proptools/proptools.go
singleton_ctx.go
unpack.go
unpack_test.go

The primary builder will now generate a rule to call itself with
--docs=.bootstrap/docs/<name>.html to produce an automatically
generated documentation file.
The documentation generation process is:
- Call each factory once to get empty property structs associated
with the module type
- Use reflection to determine the names of the type of each property
struct
- Use the bootstrap_go_package modules from reading the Blueprints files
to find the source files for each Go package used to build the primary
builder
- Use the go/parser module to find the type declaration for each
property struct
- Extract comments for the property struct and each property declaration
- Format all the comments into HTML
Change-Id: Icae9307cc10549a30bfc14d6922824099de5a9b0

Add self-documenting support

---

parser/parser.go

Add String() to print out the Comment, Text() to print out the
Comment while stripping /*, //, and */, and EndLine() to return
the line number of the last line of the comment.
Change-Id: I076bc0990143acfc03c42a8cc569894fced8ee24

Add convenience methods to Comment objects

---

context.go
parser/parser.go

Refactor parsing Blueprints and walking the Blueprints tree to
allow reuse for tasks that don't involve creating moduleInfo
structures.
Change-Id: I677857a3462999426c8306432074ea97fdcb86c8

Refactor parsing to allow reuse

---

context.go

This change fixes a bug where directories that could contain a Blueprints file
but currently do not were not being added as a dependency.  This meant that if
a Blueprints file were added to that directory it would not automatically get
picked up by the build.

Fix a sub-Blueprints deps bug.

---

.travis.fix-fork.sh
.travis.install-ninja.sh
.travis.yml

* Fix running travis on forks by moving the code around to always be gopath/src/github.com/google/blueprint
* Migrate to the container based travis setup. This should make our builds start faster according to the docs, since they can scale containers faster than VMs.
* Use ninja v1.6.0, built from source (and cached between builds).

Updates to travis config -- faster; ninja v1.6.0

---

bootstrap/bootstrap.go

Packages were defaulting to StageBootstrap, while they need to be in
StagePrimary and they'll be moved into StageBootstrap if necessary.

Fix bootstrap package build stage default

---

bootstrap.bash
bootstrap/bootstrap.go
bootstrap/cleanup.go
bootstrap/command.go
bootstrap/config.go
build.ninja.in
choosestage/choosestage.go

WARNING: API change in the first commit (bootstrap.BinDir)
To provide a consistent __FILE__ behavior with cpp, we want to be able to run with SRCDIR="." and the outputs be saved elsewhere. Other tools within android also expect to be run from $TOP.
This set of changes just removes the assumption that the build directory is always the current working directory. The defaults remain the same, unless -b or $BUILDDIR is passed into bootstrap.bash.

Support a separate build directory

---

bootstrap.bash
bootstrap/bootstrap.go
bootstrap/config.go
bootstrap/doc.go
build.ninja.in

The go compiler and linker changed in v1.5 -- to 'go tool compile' and
'go tool link' instead of 6g and 6l. Move the selection logic to
bootstrap.bash, and have it use compile/link if 6g/6l are missing. This
way the build.ninja.in will continue working with either go 1.4 or 1.5.
Travis and the test suite will fail under 1.5, since the build.ninja.in
is still generated with 1.4, and the function names in the comments
differ between 1.4 and 1.5.

Support go 1.5

---

bootstrap/bpdoc/bpdoc.go

The full package path is no longer stored in the name variable, pass the
pkg variable into getDocs and putDocs so that types with the same name
in different packages don't collide.
Change-Id: I7ecd98815487467dbaadc8a318fa43b123fc83c1

bpdoc: Cache property struct docs by full package path

---

bootstrap/bootstrap.go
bootstrap/cleanup.go

With the introduction of $buildDir in bootstrapDir, the ninja cleanup
step hasn't been able to cleanup during the bootstrap stages. The main
stage was unaffected, as long as you were using "." as your buildDir.

Fix bootstrap and separate buildDir ninja cleanup

---

Blueprints
bootstrap/bootstrap.go
bootstrap/command.go
build.ninja.in
context.go
loadplugins/loadplugins.go
module_ctx.go

Now that we have multi-stage bootstrapping, we can make the primary
builder build more dynamic. Add the concept of plugins that will be
linked and loaded into bootstrap_go_binary or bootstrap_go_package
modules. It's expected that the plugin's init() functions will do
whatever registration is necessary.
Example Blueprint definition:
bootstrap_go_binary {
name: "builder",
...
}
bootstrap_go_package {
name: "plugin1",
pluginFor: ["builder"],
}
A package may specify more than one plugin if it will be inserted into
more than one go module.

Implement go bootstrap plugins

---

bootstrap/bootstrap.go
build.ninja.in

It's difficult for wrapping scripts to handle -b properly. Just pass
BUILDDIR instead, which is easier to handle. This still accepts -b, so
that incremental builds work across this change.

"Stop using bootstrap.bash -b for separate builddir

---

Blueprints
bootstrap/bootstrap.go
build.ninja.in
gotestrunner/gotestrunner.go

This removes the need to use $OLDPWD when running tests, which means
that the builddir may be an absolute or relative directory. It also
filters out the "PASS" message on successful test runs to clean up our
output.

Add a test runner

---

context.go
context_test.go
context_test_Blueprints
module_ctx.go

walkDeps performs a pre-order DFS (unlike visitDepsDepthFirst which is
a post-order DFS). The visit function takes in both a parent and child
node and returns a bool indicating if the child node should be
traversed.

Add walkDeps to context and module_ctx.

---

context.go
context_test.go
module_ctx.go

DynamicDependencies can be implemented more flexibly by a
BottomUpMutator.  If there are no DynamicDependencies, then
EarlyMutators are identical to BottomUpMutators.  Deperecate both, and
reimplement DynamicDependencies inside a BottomUpMutator that is
guaranteed to be registered first.

Deprecate EarlyMutator and DynamicDependencies

---

module_ctx.go

TopDownMutators can visit dependencies, provide OtherModuleName and
OtherModuleErrorf so they can query and report errors on those
dependencies.

Add OtherModuleName and OtherModuleErrorf to mutators

---

module_ctx.go

PropertyErrorf gets called from build logic, and shouldn't panic if the
build logic reports an error on an unset property.  Fall back to using
the module position if the property wasn't set.
Also put the property name into the error message.

Improve PropertyErrorf

---

context.go

beforeInModuleList panic'd when checking if a variant was before itself
in the module list.  Return a real error instead of calling
beforeInModuleList, and also fix beforeInModuleList to return false for
the same module.

Print useful error for self-dependency

---

context.go
module_ctx.go

AddReverseDependencies would add modules the target's dependency list in
a non-deterministic order based on the order the modules were parsed.
Redefine AddReverseDependencies to collect dependencies until the end of
the mutator and then add them sorted by name.

Sort reverse dependencies

---

context.go

Dependency errors were prefixed with ??? because they were associated
with the position of the "deps" property, which is often not used.  Use
the position of the module instead.

Don't rely on deps property position

---

.travis.yml
build.ninja.in

Update .travis.yml to specify go 1.5.1, and update build.ninja.in to
include the new in line function names used by go 1.5.

Update travis to use go 1.5

---

context.go
singleton_ctx.go

Add VisitAllModuleVariants, PrimaryModule, and FinalModule to
SingletonContext so singletons and tools can deal with modules with
multiple variants.

Add variant methods to SingletonContext and Context

---

bootstrap/cleanup.go

An abandoned directory may have been replaced with a file, give up on
removing the directory on ENOTDIR.

End removing directories on ENOTDIR

---

bootstrap/bootstrap.go
live_tracker.go
ninja_defs.go

For implicit dependencies that will be common to all users of a Rule,
add a new field 'CommandDeps' to the RuleParam. This is a list of
strings to be prepended to the implicit dependencies in each BuildParam.
This lets us have the dependencies declared next to where they are used,
instead of duplicated in areas that may be far apart.
I looked at passing this information down to ninja too, but it only
saves us a few percent of ninja file, and requires a modification to the
ninja file format.

Add common implicit deps to Rules

---

context.go

ctx.SetBuildDir is called by the bootstrap singleton, which is always
last.  In order to allow the primary builder to set the directory for
.ninja_log/.ninja_deps, remove the panic on multiple calls to
ctx.SetBuildDir, and always used the value passed by the first caller.

Allow multiple calls to ctx.SetBuildDir

---

bootstrap/bootstrap.go
bootstrap/cleanup.go
context.go
singleton_ctx.go

Removing abandoned files needs to know where the .ninja_log file is
stored.  Export the ninja builddir value from Context and use it to
determine the .ninja_log path in any stage.
The ninja builddir (where ninja stores its .ninja_log and .ninja_deps
files) and the bootstrap.BuildDir (where build output files are written)
are distinct, so to reduce confusion replace SetBuildDir with
SetNinjaBuildDir.

Use context builddir for removing abandoned files

---

bootstrap/command.go
bootstrap/config.go

Build logic can now implement a RemoveAbandonedFiles, and the bootstrap
logic will only remove abandoned files if that method returns true.
Leaving the method unimplemented will result in the existing behavior of
always removing abandoned files.

Make removing abandoned files optional

---

bootstrap/bpdoc/bpdoc.go
proptools/clone.go
proptools/clone_test.go
proptools/extend_test.go
unpack.go
unpack_test.go

Allow property structs to contain anonymous embedded structs and
interfaces.  Properties in an anonymous embedded struct or interface are
treated as if they were properties in the embedding struct.

Support embedded anonymous property structs

---

context.go
module_ctx.go
ninja_defs.go
ninja_strings.go
package_ctx.go
scope.go
singleton_ctx.go

Turn PackageContext into an interface so that build systems can wrap it
to add more custom helpers.
This does introduce an API change, though it should be fairly simple.
NewPackageContext used to provide an opaque *PackageContext struct, now it
provides a PackageContext interface.

Allow wrapping of PackageContext

---

singleton_ctx.go

Identical to ModuleContext.Failed(), just returns whether there has been
an error added to the context.

Add SingletonContext.Failed()

---

context.go
singleton_ctx.go

Singletons may need ModuleSubDir, for example to implement a stable sort
on modules.  Add ModuleSubDir to SingletonContext and Context.

Add ModuleSubDir to Context and SingletonContext

---

context.go
module_ctx.go

In some cases the primary builder may need to handle missing
dependencies.  Add Context.SetAllowMissingDependencies to cause
Blueprint to store the list of missing dependencies without immediately
emitting an error, and ModuleContext.GetMissingDependencies to return
the missing dependencies to the primary builder.  If the primary builder
does not call ModuleContext.GetMissingDependencies Blueprint will emit
dependency errors.

Allow primary builder to handle missing dependencies

---

.travis.yml
blueprint.bash
bootstrap.bash
tests/expected_wrapper_all
tests/expected_wrapper_regen
tests/expected_wrapper_start
tests/expected_wrapper_start2
tests/test.sh

This wrapper script can be used instead of ninja to ensure the build
won't get stuck building the primary builder.
An example of when this would happen:
1. Do a successful build
2. Sync/make a change in the primary builder (soong, etc) that depends
on a blueprint change.
3. The next build would notice that change, and rewind to the primary
stage to rebuild the builder. That build would fail.
4. Sync/fix the blueprint code.
5. The next build would still fail. The bootstrap stage would need to
be run in order to fix the primary stage, but we're still stuck in the
primary stage. The only way to switch stages is to successfully
complete everything required to choose the next stage.
This generally isn't a problem in the main stage, since there is no code
being built in the dependency chain …

Add build wrapper to do stage selection before ninja

---

proptools/extend.go
proptools/extend_test.go

This makes *string values act like *bool values -- instead of appending
or prepending the contents of the string, the entire string is replaced.
The use case here is for overriding filenames, where appending doesn't
work.

AppendProperties: Replace *strings instead of appending

---

bootstrap/bpdoc/bpdoc.go

Other parts of blueprint have started allowing pointers to strings and
booleans. This code silently allowed them because of the nil check, but
it doesn't work if the module factory sets a default value.

docs: Allow propery structs to contain non-struct ptrs

---

context.go

visited map was not being updated when the dependency was being
visited, only if it was being walked. This led to cases where
duplicate traversals were possible.

walkDeps: Fixed bug on non-walked, visited deps.

---

choosestage/choosestage.go
gotestmain/gotestmain.go

Go 1.6 fixed a bug where compiling with the -pack flag allowed non-main
packages to link.
https://github.com/golang/go/issues/13468
This change uses package main for choosestage and gotestmain.

Fix package names for executables.

---

context.go
singleton_ctx.go

Our use case is to write out some configuration variables to give to our
legacy build system. But in order to do that, we either need to keep a
Go copy of all of the configuration, and still have all the calls to
convert them to ninja variables, or evaluate our ninja variables.

Add SingletonContext.Eval to evaluate ninja strings

---

Blueprints
bootstrap/bootstrap.go
bootstrap/command.go
bootstrap/config.go

Move these tools from $buildDir/.bootstrap/bin to $buildDir/bin
(configurable by the primary builder).
Also delay building them until the main stage, and give them a phony
target "blueprint_tools".

Add blueprint_go_binary for user-run tools

---

bootstrap/bpdoc/bpdoc.go
package_ctx.go
unpack_test.go

Improve readability in bpdoc by removing naming stutter.
Fixes the documented type for properties stored in pointers, previously printed as "Type: *ast.StarExpr"

bpdoc improvements

---

Blueprints
bpmodify/bpmodify.go
build.ninja.in
context.go
parser/ast.go
parser/modify.go
parser/parser.go
parser/parser_test.go
parser/printer.go
parser/printer_test.go
parser/sort.go
unpack.go
unpack_test.go

Refactor the blueprint parser Value object, which contained a Type enum
and members to hold every possible type, into an interface (now called
Expression).  Rename the existing Expression object that represented a binary
operator Operator.
Also adds and fixes some new printer test cases with mulitline expressions.
Change-Id: Icf4a20f92c8c2a27f18df8ca515a9d7f282ff133

Refactor blueprint parser nodes to an interface

---

parser/printer.go
parser/printer_test.go

There may be multiple skipped comments in a row, convert
p.skippedComments to a list and add a test.
Change-Id: I30dcff269bee56fd51ef9513dab7c7885c44b7d7

printer: support multiple skipped comments

---

parser/printer.go
unpack.go

value.Type and value.Pos changed to methods, change the users that were
not caught by error checking to use Type() or Pos().
Change-Id: I295a658c007fa2de68c89fb85ee367fbea5ed1aa

Fix error messages containing variable types

---

module_ctx.go

It can be useful for a BottomUpMutator to visit its dependencies.  Embed
all of TopDownMutatorContext into BottomUpMutatorContext.
Change-Id: I7c7262fbe3d8fa9cc0d26899eee704cc862835df

Add dependency visiting methods to BottomUpMutatorContext

---

context.go
singleton_ctx.go

In order to implement some build statistics in Soong, expose the module
type (the string used to define the module) to singletons.

Expose ModuleType to Singletons

---

bootstrap/bpdoc/bpdoc.go
bootstrap/command.go
proptools/clone.go
proptools/extend.go
proptools/extend_test.go
proptools/typeequal.go
proptools/typeequal_test.go
unpack.go
unpack_test.go

Reduce primary builder times with two optimizations in proptools:
1.  Cache results of reflect.Type.Field() to avoid the garbage produced in reflect.StructField.Index
2.  Allow nil pointers to concrete struct types in properties to reduce allocating and copying empty structs
Also adds a -trace argument to the primary builder to allow tracing of concurrency.

Optimize proptools

---

.travis.gofmt.sh
.travis.yml
ninja_defs.go

Run gofmt -l . during travis to catch pull requests that have not had
gofmt run on them.
Change-Id: Ibfdf988a535d82721f3c4bc328b189f606f12778

Enforce gofmt in travis

---

context.go
module_ctx.go
ninja_defs.go
splice_modules_test.go

Profiling shows BottomUpMutators and cloneModules as the slowest parts of Soong, primarily due to lack of parallelism.  Allow primary builders to request BottomUpMutators to run in parallel, and always parallelize cloneModules.

Add concurrency to BottomUpMutators and cloneModules

---

context.go

Don't add a "_" to the variant name if the variation name is empty.  For
example, when splitting a variant with name "foo" into variations "" and
"bar", the new variants would be named "foo" and "foo_bar" instead of
"foo_" and "foo_bar".
Change-Id: I82342d57e2a8e9f2d65a7d8d2872dcb7b3512899

Elide empty variations

---

proptools/extend.go
proptools/extend_test.go

Allow using ExtendMatchingProperties to extend pointer to a struct or an
interface containing a pointer to a struct using a struct, and
vice-versa.
Also fixes a pre-existing bug where extending a nested structure could
fail if there were multiple possible destnations and some of them did
not have a matching nested property.
Change-Id: I6e69d78eb6595ba7dd2603e3aa7dd8de3f292744

Relax type requirements when extending properties

---

package_ctx.go

Allow Blueprint build statements and rules to reference rules and pools
defined outside of Blueprint.
Change-Id: I48644497d16a4c2bab88db400dbe7f7fe169d933

Add NewBuiltinRule and NewBuiltinPool

---

unpack.go

In Go 1.7, all generated types (including StructOf) are marked as
unexported types. This is not a problem with regular named fields, since
the whether the field is exported is based on the name, not the type.
But for unnamed (anonymous) fields, there is no name, and it falls back
to whether the type is exported or not. When the field isn't exported,
we're unable to use reflection to set the value.
Special case fields named "BlueprintEmbed" to act like exported unnamed
fields during unpacking. There is no functionality lost here, since code
can not directly access these runtime generated fields.
Structures embedded in the source shouldn't be affected by this change,
unless they happen to use the "BlueprintEmbed" field, which is not a
normal field name due to the capitalization.

Support structures built with StructOf

---

Blueprints
build.ninja.in
proptools/escape.go
proptools/escape_test.go

Blueprint properties that end up as command line arguments need to be
both ninja and shell escaped.  Provide helpers that primary builders can
use to appropriately escape them.
Change-Id: Ifd697d87edb1c6f0a910377835c391bbe8f95b42

Add proptools functions to escape strings

---

context.go

Blueprint files included with build= statements were not adding a
dependency to cause regenerating when they were changed.
Bug: 32085516
Test: touch external/boringssl/sources.bp && mmma -j external/boringssl
Change-Id: Id4fdf3b6788ae5c1e94547dc63ec6b55424a66a0

Add dependency on build= blueprint files

---

bootstrap/command.go

Add -memprofile argument to support capturing a heap profile, and -nogc
to disable the garbage collector to see all allocations.
Change-Id: I0d4c5f2bf79786aed4b2af4be112ecf0a2810a91

Add support for memory profiling

---

bootstrap/bootstrap.go
context.go
context_test.go
module_ctx.go
visit_test.go

This patch set allows primary builders to have control over the name visible to Blueprint, to determine if a module with a name exists, to rename a module during a mutator, and to replace dependencies on a variant of module with another module.

Modify module name handling

---

blueprint.bash
bootstrap/bootstrap.go
build.ninja.in
tests/test.sh

Soong (and soon, Blueprint, with #131 ) embeds the results of filesystem globs into the build.ninja, and uses a helper tool to detect when the glob changes and we need to rebuild the build.ninja file. This is more flexible than listing the affected directories in the depfiles, since it can check to
see if a file we actually cared about was added, instead of re-running anytime any file was added/removed (which happens on atomic file modifications as well).
My recent bootstrap simplification broke this, since the helper rules are in the main build.ninja, but I removed the ability to regenerate that file from itself. So keep the current model, but add a rule into the primary and main stages that allow themselves to re-run their generator and write out a new build.ninja file if necessary. The …

Fix Soong glob regeneration and other bootstrap cleanups

---

pathtools/glob.go

Sometimes os.Stat on a path seems to return nil after filepath.Glob
returned the path as valid.  Return the error message to see why.
Bug: 32676828
Test: builds
Change-Id: Ieedddb673b4d641e5de08778febeb3d8ea025c0d

Add better error message when stat returns nil

---

context.go
pathtools/glob.go

Bypassing c.glob() and using filepath.Glob() directly for non-glob
paths does not add dependencies on directories that contain missing
files.  For optional_subdirs, this means no dependency is added to
rerun the primary builder when an Android.bp file is added to an
optional_subdirs directory.  Always use c.glob(), for the non-optional
case it will not insert any dependencies if the file exists (as tested
by glob_test.go's no-wild tests), and if the file doesn't exist the
len(matches) == 0 will error out.
Change-Id: I370479c6e89f5ff590897702e256256a4dca6952

Fix optional_subdirs globbing

---

pathtools/glob.go
pathtools/glob_test.go

Hidden files are often source control related (".git", ".repo", etc) or
editor related (vim's .*.swp), so are not guaranteed to exist, and may
be temporary. The build system shouldn't be using these files by
default.
If the glob pattern explicitly uses "." at the beginning of a path
component, allow returning hidden files for that component. Because of
this behavior, non-wildcard globs remain unchanged.
The one behavior that cannot be handled anymore is including hidden
files in recursive globs.

Prevent glob from accessing hidden files

---

bootstrap/bootstrap.go
gotestmain/gotestmain.go
gotestrunner/gotestrunner.go

A few changes that were needed when I was writing tests for some Soong tools:
* Actually running tests for tools built during the main stage
* Making -test.run work for the test binaries (used to test os.Exit scenarios by re-executing the current binary)
* Fixing GOROOT during test runs

Improve testing tools

---

gotestmain/gotestmain.go

f.Scope.Objects is a map, so iteration order isn't defined. To fix this, lets just sort the testcase list so that it's always consistent.
There are still some paths in the built go files, but this improves repeatability using the same paths.
Test: Build twice, compare generated test.go files.

Sort testcases to make build (more) reproducible

---

context.go
module_ctx.go

It is not allowed to directly use BaseDependencyTag as customized user dependency tag passed down to Blueprint since it might cause issues that different type of modules will be mixed when fetched based on Tag.

Added a check in Blueprint level for BaseDependencyTag

---

bootstrap/bootstrap.go

When only linux/darwin tests were specified, we weren't setting testArchiveFile, so we had a corrupted ninja file (build : ...).

Fix bad ninja file if only GOOS-specific tests exist

---

context.go

Instead of just saying:
```
error: .../Android.bp:48:1: dependency "libc++" of "libtest" missing variant "arch:android_arm_armv7-a, link:shared, vndk:"
```
Include a list of currently existing variants:
```
error: .../Android.bp:48:1: dependency "libc++" of "libtest" missing variant:
arch:android_arm_armv7-a, link:shared, vndk:
available variants:
arch:android_arm_armv7-a, link:shared
arch:linux_x86, link:shared
arch:linux_x86_64, link:shared
arch:windows_x86, link:shared
arch:windows_x86_64, link:shared
```
This still isn't the best experience for users, but it at least provides enough information for someone more familiar with the build to understand the problem.

Improve error messages when dependency variants are missing

---

live_tracker.go
ninja_defs.go
ninja_strings.go
ninja_strings_test.go

Allow the ninja description variable to be set on build statements
as well as rules.
Escape leading space in ninja strings

Allow BuildParams to override ninja description

---

pathtools/glob.go
pathtools/glob_test.go

Patterns that were not wild would return an empty "dirs" list if the
file was found. But then if they were removed, we wouldn't know to
update the glob file and re-run the primary builder.
In this case, instead of adding the final directory into the dirs list,
add the matched files themselves. Due to editors performing atomic
writes (the directory timestamp often gets updated at the same time as
file timestamp) this is probably more efficient. In either case, we're
only re-running the individual glob, which is rather cheap.
Rename startGlob/Glob return name from "dirs" to "deps" since it may
contain files now too.

Fix glob deps for non-wild patterns

---

.travis.yml
Blueprints
build.ninja.in
gotestmain/dummy.go
gotestmain/gotestmain.go
gotestmain/testmain_test.go
regen_build_ninja_in.sh
tests/test_tree/build.ninja.in
tests/test_tree_tests.sh

If tests have a TestMain method the os import is unused and
breaks building the test.
Test: gotestmain/testmain_test.go
Change-Id: Ia46cdd0df71b0fc7a53d08644d220ecfd779b2ff

Fix tests with TestMain

---

pathtools/fs.go

Add the final directory to MockFs so that Exists() on . and /
returns true.
Test: java_test.go
Change-Id: I1320f4f267ee6b6a7dbf1132630df306602e84d8

Add . and / to MockFs

---

.travis.yml
blueprint_impl.bash
bootstrap/bootstrap.go
gotestmain/gotestmain.go
microfactory/microfactory.go

Tell travis to test go1.9beta2, fix the build break in gotestmain, and enable the new parallel compilation support in the go compiler.

Go 1.9 changes

---

context.go
pathtools/fs.go

Bug: 64600838
Test: mkdir errtest \
&& ln -s /tmp/dontexist errtest/Android.bp \
&& m nothing \
Change-Id: I841ec12d613f61ccc3396538062bee48c8c1ca27

Clearer error in case of Android.bp being unreadable

---

tests/test_tree_tests.sh

This should prevent the running of Travis tests from causing
a filesystem loop src.test/test_tree/blueprint -> ../..
(except if the test unexpectedly exits)
Bug: 63100441
Test: NINJA=... ./tests/test_tree_tests.sh; stat src.test 2>/dev/null \
&& echo "src.test should not exist"
Change-Id: Ie01fe8999c738dca166e3fabde9d9391f6b70210

Remove src.test after running Travis tests

---

.travis.yml
bootstrap/command.go
context.go
context_test.go
module_ctx.go
proptools/extend.go
unpack.go
unpack_test.go
visit_test.go

Allow a module to create other modules as if they were specified
in a blueprint file.  CreateModule takes the name of a module type,
calls the factory function the module type, and then inserts
properties into the property structs returned by the factory.

Add TopDownMutatorContext.CreateModule

---

pathtools/fs.go
pathtools/glob.go
pathtools/glob_test.go

Recursive globs on MockFs were ending up in an unmocked os.Lstat
call in walkAllDirs.  Move walkAllDirs into the FileSystem interface
as ListDirsRecursive.
Also duplicate the glob tests on both the real filesystem and on
MockFs.
Change-Id: Ia6b6b5eecdd17955a49d684a0fd5e55df05cfe62

Fix recursive glob on MockFs

---

live_tracker.go
ninja_defs.go

Commands that contain tools that don't affect the build results
may want an order-only dependency on the tool.  Allow rules
to specify order-only dependencies the same way they specify
implicit dependencies.
Test: builds
Change-Id: I3e0f886ae047b0fadf7a5c0dfeb9827d2c5c411d

Allow rules to specify order-only dependencies

---

microfactory/microfactory.go

To prevent against multiple instances attempting to rebuild the same executable, add a file lock to Build().
The trace file may not be consistent in this case, but everything that reads it should be able to handle a corrupted trace file.
Test: `while true; do <microfactory-enabled executable>; done` in parallel, and modify the code to microfactory (echo "//" >>microfactory.go)

Add file locking to microfactory

---

Blueprints
doc.go
tests/test_tree/Blueprints

An ill-fated experiment with using a format that was closer to
Bazel left Blueprint preferring the original style, but documenting
and using the new style.  Update the documentation and run bpfmt -w.
Test: builds
Change-Id: I3fb70c8fa50c332da01cf5912b179c60d1638814

Finish switching blueprint back to the original Blueprints format

---

module_ctx.go

When a mutator calls CreateModule, set the blueprints file and line
number to the values of the module that the mutator was visiting.
Change-Id: I4526f14a744be944e42582bc46f11a9a7b502f03

Set fields in CreateModule to match current module

---

parser/ast.go
parser/parser.go
parser/parser_test.go
parser/printer.go
parser/printer_test.go
proptools/clone.go
proptools/clone_test.go
proptools/extend.go
proptools/extend_test.go
proptools/proptools.go
unpack.go

Support int64 number instead of int to be more fixed to num of bits so that the underlying arch won't affect overflow cases. Besides, refection: func (v Value) Int() int64 always cast to int64 no matter the input is int, int16, int32. Currently we always treat "-" as negative sign to bind to next value, and "+" as plus operator to add operands together.
So we allow:
a = 5 + -4 + 5 or a = -4 + 5
But we don't allow:
a = +5 + 4 + -4 since we don't treat "+" as a positive sign, otherwise,
a = 5 + +5 would exist which looks pretty weird. In the future, we may want fully support number calculator logic eg, "+"/"-" can be positive/negative sign or operator, and "(" and ")" will be considered to group expressions with a higher precedence.
int & uint properties within struct keeps unchanged, which …

Support parsing int64 number in Blueprint file

---

context.go

PreSingletons use the same interface as Singletons, but run after
parsing all the blueprint files but before running any mutators
or GenerateBuildActions.  They can be used to perform global setup,
including generating rules, that may be referenced by later
mutator or generate passes.
Change-Id: I4b93425a724e739f5b8843262efb8804b3bf3531

Add presingletons

---

pathtools/glob.go

Export pathtools.Match so that tools that operate on file lists
(like zip listings) can use the same glob format.
Change-Id: Ic4b90139c381c57551836590da3ea54826b0227a

Export pathtools.Match

---

Blueprints
context.go
context_test.go
module_ctx.go
name_interface.go
visit_test.go

to facilitate moving name resolution to Soong
Bug: 65683273
Test: build/soong/scripts/diff_build_graphs.sh \
--products=aosp_arm \
'build/blueprint:work^' 'build/blueprint:work'
Change-Id: Ifa7603cca59b3b3d592f2f146fdafe57012bd4b9

Extract module naming into an interface

---

bootstrap/bootstrap.go
bootstrap/build.ninja

We're already going to load the .ninja_deps file, so we may as well use it. These are the only two files in our build that don't.
Test: dump the .ninja_deps file, see the dependencies

Store build.ninja deps in .ninja_deps

---

Blueprints
glob.go
glob_test.go

Performing the same glob twice, once with excludes=nil and once
with excludes=[]string{} would hit the same entry in the glob
cache (since the glob filename would be the same), but fail
the verifyGlob check because DeepEqual considers []string(nil)
and []string{} to be different.  Use a manual array check
instead.
Change-Id: If0d4fe80163a871077b7276e1b4a3e888a4a4898

Fix glob cache conflict when excludes=nil and excludes=[]string{}

---

context.go
module_ctx.go
pathtools/glob.go
pathtools/glob_test.go
singleton_ctx.go

This makes it easy for users of Glob to detect whether the match is a file or directory. Doing the check at this level means that the filelist file used as a dependency will be updated if a directory is replaced with a file of the same name, or vice versa.

Append / to directories in Glob results

---

.travis.yml
context.go
gotestmain/gotestmain.go

Add stubs for the new testDeps interface functions. Also removes testing for 1.8.

Support go1.10

---

bootstrap/config.go

In Go 1.10, runtime.GOROOT() will attempt to find the current location of the go binaries, instead of using the GOROOT_FINAL that was baked into the binaries. This means that GOROOT() will usually return an absolute path.
We avoid putting absolute paths into the ninja file, since any change to the paths would then cause all of the actions including it to rebuild. Since we've got a decent number of build tools in Android using Go now, this causes us to rebuild a decent portion of the tree.
Instead of passing the GOROOT around manually in a side channel, just let the Go 1.10 detection do its thing, and always try to turn the result into a relative path.

Try to make GOROOT relative in Go 1.10

---

bootstrap/bootstrap.go

When passing "-c" to the Go compiler, any time this value changes, we'd force all of the Go compiles to rebuild. This could trigger a substantial portion of the tree to rebuild (anything that transitive depends on a Go helper tool).
We're running into issues when moving output directories between multiple GCE machines with different core counts, but are otherwise identical. This could also hit users moving/mounting disks between machines, though changes to other host tools can make an impact too.
On my 48-core machine, I get a ~15% benefit from going from -c 1 to -c 48, but also ~12% benefit from going from -c 1 to -c 8. So this will still let us scale somewhat, but prevent rebuilds when transitioning between machines that are more likely building Android.

Cap the number of cpus for Go compiles

---

microfactory/microfactory.go

These options aren't compatible with one another.

Disable parallel compilation when using race detector

---

parser/printer.go
parser/printer_test.go

When someone used a multiline string:
```
cmd: "..." +
"...",
```
bpfmt used to print this out as:
```
cmd: "..." +
"...",
```
This change doesn't do the quote alignment like I see in some of our
user-created instances of this, but it does indent a single level:
```
cmd: "..." +
"...",
```
Test: unit tests
Test: Compared bpfmt results before and after across AOSP

Improve indentation for multi-line expressions

---

context.go
context_test.go
module_ctx.go
visit_test.go

Allow adding multiple dependencies on the same module.  Adds a flag
to Context.walkDeps to determine whether dependencies should be
visited multiple times, and clarifies the behavior of
VisitDepsDepthFirst (continues to visit each module once, even if
there are multiple dependencies on it) and VisitDirectDeps (may
visit a module multiple times).
Test: TestWalkDepsDuplicates, TestVisit
Change-Id: I58afbe90490aca102d242d63e185386e1fe55d73

Allow multiple dependencies on the same module

---

context.go
context_test.go
module_ctx.go

WalkDeps was following every possible path through the dependency
tree, which can be enormous.  Modify it to only call visit for
any particular (child, parent) pair once for each direct dependency
by not recursing into child if visitDown returns true but child
has already been visited.
Test: TestWalkDeps, TestWalkDepsDuplicates
Change-Id: Ieef28399bd10e744417cdeb661dfa04fbeb4ec60

Prevent duplicate visit calls in WalkDeps

---

pathtools/glob.go
pathtools/glob_test.go

pathtools.Match was trimming the trailing slash from patterns.  Make
it handle a trailing slash by first confirming that both the pattern
and name either both have or both do not have a trailing slash, and
then trimming it from both.
Bug: 111389216
Test: TestMatch in glob_test.go
Change-Id: I743e00c14d885de5b5a060aa9e2b22c81dc7e09d

Support trailing slash in pathtools.Match patterns

---

bootstrap/bootstrap.go
context.go
go.mod

go1.11 adds module support, so that modules & packages can be used outside of $GOPATH. So add the file declaring this the module for github.com/google/blueprint, and fix some issues found by `go vet`.

Add go1.11 go.mod and fix `go vet` issues

---

singleton_ctx.go

If a panic occurs in SingletonContext.VisitAllModules report the
module that was being visited.
Change-Id: Ia7fc07e2e33e9e3c0297903d3b06b7efb33f0105

Report panic context for SingletonContext.VisitAllModules

---

pathtools/glob.go
pathtools/glob_test.go

Globs that match a file that looks like a glob were causing duplicate
results because the prefix match would then re-match the
filename as a wildcard.  Add escaping to prevent re-matching.
Also add tests for globs on files with wildcards, tests for
? and [a-z] glob matches supported by filepath.Match, and tests
for escaped wildcard characters.
Change-Id: Id11a754863979bb36cca0dbd18ea2e76dd1470e3

Fix globs matching files with wildcard characters in the name

---

context.go
context_test.go

Throw an error if run into a module without a name when generating
contexts.
Test: context_test.go
Change-Id: I3976d86d1f15b8ac10a7a38aa42ae277740a8f3b

Make sure all modules have a name.

---

bootstrap/bootstrap.go

The test package archive was being picked up through "-L" + testRoot,
but did not have a dependency on it.  If the *_test.go file was
changed but not the implementation then the tests would not be
rerun.
Test: Add t.Fatal() to a *_test.go file and rebuild.
Change-Id: I32b8c7a0fa1d5b76b1242646887fe937e396e318

Add link dependency on test package archive

---

bootstrap.bash
bootstrap/bootstrap.go
bootstrap/command.go
bootstrap/config.go

In cases that we want to run blueprint-based builds in many configurations to verify all of the logic works without errors, but don't care about running the final ninja file, writing it out only wastes time and disk space. So add a --empty-ninja-file option that writes out an empty ninja file instead.
Our specific use case (Soong's build_test / multiproduct_kati) runs Soong several hundred times for different configurations, and the ninja files are around 1GB, which leads to several hundred gigabytes of disk writes (and persistent use during incremental generation).

Add --empty-ninja-file for test usecases

---

bpmodify/bpmodify.go

before, adding to a list which had no entries would do nothing (and not
throw any errors). Now it will create the list and add a single element
as expected.
Change-Id: I8c48a42303f7d9b3741868ad86097e2071ec434a

bpmodify: add argument if it is missing

---

context.go
singleton_ctx.go

Add Context.Singletons and Context.SingletonName to allow primary
builders to query Singletons returned by all registered
SingletonFactories.
Change-Id: Iee85643dd47f7472e6bb5ae8004374bd6ea0419e

Allow Context to query Singletons

---

module_ctx.go

GetDirectDeWithTag would panic if the first possible directDep did not
have the correct tag. It should check to see if any version of that
dependency has the right tag.
Test: atest CtsJdwpTunnelHostTestCases
Bug: 124507633
Bug: 125933724
Change-Id: I00d269130e9f136a93fd30c58b8fd929372d5b37

GetDirectDepWithTag needs to check all tags before panicing

---

proptools/escape.go
proptools/escape_test.go

NinjaEscape and ShellEscape operated on lists, which led to
awkward NinjaEscape([]string{s})[0].  Replace NinjaEscape
and ShellEscape with NinjaEscapeList and ShellEscapeList,
and add new NinjaEscape and ShellEscape functions that
operate on a string.
Change-Id: I283d92cdddc8e0066a300015863a3eab66f77c23

Replace *Escape with *EscapeList

---

Blueprints
proptools/proptools.go
proptools/tag.go
proptools/tag_test.go

Add a function that returns all of the indexes to properties in
a property struct that are tagged with `name:"value"`.
Test: proptools/tag_test.go
Change-Id: I00294934c1a0383c8b64ecaabc0e138682efb2e5

Add PropertyIndexesWithTag

---

proptools/clone.go

When CopyProperties comes across private properties, it silently ignores
them. This is error-prone and can result in a bug very hard to debug if
the developer is unaware of the behavior.
Change-Id: Id6a0752e384ec7fed35728c1e87dbfa95fea84f2

Panic when copying private properties.

---

context.go

The go comment for the blueprint.Context.ParseBlueprintsFiles was
actually place above the blueprint.Context.ParseFileList.
Change-Id: I065d2f6ec034c614e40de745931f4c87cdb73422

Moving the ParseBlueprintsFiles go comment in context.go.

---

bootstrap/bpdoc/bpdoc.go
bootstrap/bpdoc/properties.go
bootstrap/bpdoc/reader.go
bootstrap/bpdoc/reader_test.go

1. Apply preformatted text (<pre>...</pre>) handling logic to module
type text too. It used to be applied to property texts only.
2. Improve <pre> handling logic itself for better readability.
- Insert a blank line before <pre>.
- Prevent from ending <pre> blocks prematurely by checking if an
unindented line isn't just a blank line between indented lines.

bpdoc preformatted text improvments

---

bpfmt/bpfmt.go

bpfmt was always exiting with return code 0, make it use the
exitCode recorded when reporting errors.
Also use the usage function.
Test: bpfmt -o bpfmt.go
Test: bpfmt
Test: bpfmt -h
Fixes: 113069050
Change-Id: I717d524c5f43cd36f52e33964a37324cc04c5df0

Correctly report errors in bpfmt

---

bootstrap/bpglob/bpglob.go

bpglob is only used as a helper to check if the primary builder
needs to rerun due to the results of a glob changing.  A recent
change to glob support in pathtools made a glob format that was
accidentally previously accepted into an error.  If the bad
syntax was used in the most recent primary builder run, and
then an incremental build is performed after picking up the
change that made the syntax invalid, then bpglob will attempt
to rerun before the primary builder, see the now-invalid syntax,
and fail.  This will prevent the primary builder from rerunning,
which would have updated the bpglob rule with a corrected glob
syntax (or failed in the primary builder if the Blueprints file
still had the invalid glob syntax).
Avoid exiting with an error in bpglob.  Instead, write the
error to the …

Avoid exiting with errors in bpglob

---

Blueprints
bootstrap/bpdoc/bpdoc.go
bootstrap/bpdoc/bpdoc_test.go
bootstrap/bpdoc/properties.go
bootstrap/bpdoc/properties_test.go
bootstrap/bpdoc/reader_test.go

This change fixes a bug where the `blueprint:mutated` tag was ignored
when used for struct or interface properties. It also fixes a dormant
ExcludeByTag func bug.
Test: m soong_docs, properties_test.go, bpdoc_test.go
Change-Id: I926de2aa203ec552ced897174e9b78e817701a7d

Skip mutated struct properties in bpdoc.

---

proptools/extend.go

These are useful outside the package too when calling
proptools.ExtendMatchingProperties.
Change-Id: I054eb105e0dd5287aff99b8be137a8b09d52492d

Make off-the-shelf order funcs public.

---

bootstrap/bootstrap.go

The primary builder should always be running on its own with no
other processes running in parallel, so put it in the console
pool so that it can print to stdout without buffering.
Bug: 80165685
Test: build with print in Soong
Change-Id: If34ecdb5fa18de7e47c4cd6965d551c504850176

Put the primary builder into the console pool

---

module_ctx.go

Allow querying the mutator name for debugging.
Bug: 136473661
Change-Id: I6a9f1f8cc4fd456d32cc2f2ef85a497c193d7e09

Add MutatorName to mutator contexts

---

bootstrap/bootstrap.go

This reverts commit 8ea996f61dd4f10e0cef5e2dc328dc071c3b7db5.
Having the primary builder hinders automatic error reporting
by separating the error message from the failure status.

Revert "Put the primary builder into the console pool"

---

context.go
module_ctx.go

SetDefaultDependencyVariation sets the variation name that will be used
when a dangling dependency is found while a module is being split. A
dangling dependency can occur if a module is split to a variant that one
of its dependencies is not split into. When the default variation is not
set, such dangling dependency is a hard error. But with the new
function, the default variation can be set and subsequent calls to
CreateVariations and its variations on the same context uses the default
variation when necessary.
(If even the default variation does not exist for the dependent module,
it is an hard error)
Note that this is different from calling SetDependencyVariation("foo")
followed by CreateVariations("foo", "bar"). In that case, regardless of
whether a dependency of the current module has …

Add SetDefaultDependencyVariation

---

package_ctx.go

This function checks if it is called from init() by looking into
callers. By the way, it may fail when init() is inlined.
To fix this, CallersFrames() is used to translate PCs into symbolic
information accounting for inlined functions.
Test: go test ./...
Change-Id: I18b3c3ffdaf71f775e3522c87607aec5df7b09c5

Fix checkCalledFromInit

---

singleton_ctx.go

A an example use case is generating the graph of module
dependencies, where modules are vertices and dependencies
are edges.
The patch was tested with a local implementation of such
a module in the Soong build system. The graph was generated
for all modules in the AOSP tree.

Added VisitDirectDeps* methods to SingletonContext.

---

Blueprints
context.go
context_test.go
module_ctx.go
module_ctx_test.go
visit_test.go

Adding a dependency on a module with variants can be problematic if the code adding the dependency is not aware of every mutator that has created variants.  Add an AliasVariations to BottomUpMutatorContext, which allows a mutator to alias the original variant of a module to one of the new variants of the module, which will allow future dependencies to be added using the original list of variations.  The aliases are transient, and only exist until the next mutator that calls CreateVariations when visiting the module without also calling AliasVariations.

Add support for module variant aliases

---

proptools/extend.go
proptools/extend_test.go

override_* in Soong requires a module to override certain properties of
other module. In that case, values of a slice property (e.g. []string)
should be replaced by the same property value in the overriding module.
However, since proptools only supports Append and Prepend orders where
the original values are kept for slice properties, the behavior
couldn't be implemented. To support the use case, Replace order is
introduced, in which case slice property values are completely replaced.
For other types of properties, the Replace order behaves exactly the
same as the Append order.
Bug: 144338929
Test: m
Change-Id: Iae9feda035177fe6a22e6e8319c0fdaa9e08e85e

Slice properties can be replaced

---

context.go

Allow the primary builder to set the filesystem directly.
Bug: 146437378
Change-Id: Ic8cc3e6a03943d5f47b041a66df6a11f4336c97b

Add Context.SetFs

---

module_ctx.go

EarlyModuleContext already has ModuleDir, add BlueprintsFile too.
Change-Id: Ia9e0c724562e1461dfcd5e01f56ff8abbea2ac06

Add EarlyModuleContext.BlueprintsFile

---

bootstrap/command.go
bootstrap/glob.go

Two issues with globs were causing unnecessary primary builder reruns on an incremental build after a clean build or after changing a glob result.

Speed up incremental builds after globs

---

bootstrap/bpdoc/bpdoc.go
proptools/filter.go
proptools/filter_test.go
proptools/unpack.go
proptools/unpack_test.go

FilterPropertyStructSharded was just sharding the top level
properties into groups of 10.  For nested property structs
this can be insufficient - there could be a single top level
property with many properties below it.
Take a maximum name size, and track the size used by parent
structs to determine when sharding a nested struct is necessary.
Bug: 146234651
Test: filter_test.go
Change-Id: I5b5ed11ea27a0325b2fd6c2c3fb427ea1e2af0c2

Make FilterPropertyStructSharded smarter

---

parser/ast.go
parser/parser.go
parser/parser_test.go

Parser.parseVariable method should always set the value of the variable
it creates. Failure to do so may end up in the following:
```
$ androidmk  <(printf "FOO:=(X)\nFOO:=bar\n")
parse error:
<input>:3:1: variable already set, previous assignment: FOO@<input>:1:5 = %!s(PANIC=String method: runtime error: invalid memory address or nil pointer dereference) (%!s(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)) false
```
The cause is that calling Parser.Parse to parse `FOO=abc` created
a Variable instance with nil value, causing panic on print attempt.
Test: m androidmk && androidmk  <(printf "FOO:=(X)\nFOO:=bar\n")
(should print:
ERROR:  parse error:
<input>:3:1: variable already set, previous assignment: FOO@<input>:1:5 = X = Not Evaluated (X = Not …

Fix null pointer dereference printing an expression.

---

context.go
proptools/clone.go
proptools/clone_test.go
proptools/extend.go
proptools/filter.go
proptools/proptools.go
proptools/tag.go
proptools/unpack.go
proptools/unpack_test.go

The proptools functions took an inconsistent variety of struct and *struct types.  Some methods even took a struct but returned a *struct.  Make all the exported methods take a *struct, with internal helpers for the ones that need to take a struct.

Proptools consistency

---

context.go
live_tracker.go
ninja_defs.go
ninja_strings.go
ninja_strings_test.go
package_ctx.go
scope.go

There are 8935901 *ninjaString objects generated in an AOSP
aosp_blueline-userdebug build, and 7865180 of those are a literal
string with no ninja variables.
Each of those *ninjaString objects takes a minimum of 48 bytes for
2 slices, plus 8 bytes for the pointer to the ninjaString.  For
the literal string case, one of those slices has a single element,
(costing another 16 bytes for the backing array), and the other
slice is empty, for a total of 72 bytes.
Replace *ninjaString with a ninjaString interface.  This increases
the size of the reference from 8 bytes to 16 bytes, but using
a type alias of a string for the literal string implementation uses
only 16 bytes, saving 40 bytes per literal string or 314 MB.
Test: ninja_strings_test
Change-Id: Ic5fe16ed1f2a244fe6a8ccdf762919634d825cbe

Make ninjaString an interface

---

proptools/proptools.go
proptools/proptools_test.go
proptools/unpack_test.go

Soong config variables may propagate an uppercase name from Make.
Blueprint properties have traditionally been all lowercase, and
using an uppercase property struct field name resulted in a strange
Blueprint property name with the first rune lowercase and the
remaining runes uppercase.
Update the rules for proptools.PropertyNameForField to not lowercase
the first rune if the field name has mulitple runes and is not all
uppercase.
Fixes: 148865218
Test: proptools_test.go
Change-Id: I8de2f65ffb00e5a8ce0aea0caf09f5859315f6b8

Support unpacking capitalized property names

---

proptools/proptools.go
proptools/proptools_test.go

Field "X86" has no lowercase runes and was being left uppercase.
Change the new PropertyNameForField rules to lowercase the name unless
it has any uppercase rune after the first rune (which is always
uppercase) and no lowercase runes.
Bug: 148865218
Test: proptools_test.go
Change-Id: Ifd1c10fc03f5ae1765d25b3f73dba8fd61c5c956

Fix PropertyNameForField for X86.

---

context.go

Mutators were not propagating the results of ctx.AddNinjaFileDeps.
Test: examine out/soong/build.ninja.d
Fixes: 150689149
Change-Id: Ia1e69ebc9dfa94a05f4ecd9cc2a8691ee63c9dd5

Fix missing dependencies from mutators

---

proptools/unpack.go
proptools/unpack_test.go

Property value should be evaluated before property map is populated with
it. Added the test for this case.

Fix bug in buildPropertyMap in previous commit.

---

bpmodify/bpmodify.go

golang `flag` package's default FlagSet `flag.CommandLine` calls
`flag.Usage` and `os.Exit(2)` on error to print the usage string.
Set `flag.Usage` to our custom usage function.
Test: m bpmodify; bpmodify -h; bpmodify --help
Change-Id: Ida107b0dbb07c291c3d7ea90eda9147d04a7cd51

Set bpmodify usage function

---

bpmodify/bpmodify.go

main() method calls os.Exit(exitCode) upon return, respecting any
exitCode set by the report() method.
Test: bpmodify -w; echo "$?"
Test: bpmodify Android.bp; echo "$?"
Test: # echo command should output "2"
Change-Id: Iaf056301eaba3f249b256ecf0f0d87f8a4df1c58

bpmodify: respect exitCode

---

bpmodify/bpmodify.go

The `defer func() { os.Exit() }()` in main() method shadows panic().
Make the exit handler recover() from panic(), log the panic(), and then
gracefully exit.
Test: m bpmodify
Change-Id: Icc89f8fce0b6096489baa0ba0f08c21d1ef623bc

bpmodify: fix os.Exit() shouldn't shadow panic()

---

context.go
context_test.go

Previously, WalkDeps() would record that a module was visited after the
first time it encountered the module irrespective of whether it recursed
into or not. This change moves the recording so it happens only after it
has been recursed into.
Added TestWalkDepsDuplicates_IgnoreFirstPath to test the change. Without
the change the test fails because it does not visit E.
Test refactoring:
* A depsMutator was added instead of relying on blueprintDepsMutator to
allow different tags to be used for different dependency types.
* Modified barModule and fooModule to support the new depsMutator and
add support for another type of dependency that is ignored by the
walking code.
* Extracted walkDependencyGraph() function to reuse common code.

WalkDeps - only record module visited when it has been recursed into

---

bootstrap/command.go

Otherwise we'll re-run the primary builder every time this is used. This triggered my new ninja checks that verify that all commands write their outputs.

Actually write an empty ninja file with --empty-ninja-file

---

context.go

Previously a LoadHook could not modify the name of a module because the
module was registered before the LoadHooks were run. That made it very
complicated (requiring mutators and auto generated names) to create a
module type whose name was determined by say the directory in which it
is defined.
This change moves the LoadHook execution slightly earlier so it runs
before registration of the module.
That caused one slight side problem which was that the
LoadHookContext.ModuleName() method would fail when called in a
LoadHook. That was because ModuleName() calls *moduleInfo.Name() which
gets the name from moduleInfo.group.name but that resulted in a panic
as group was nil because it is only set when the module is registered.
Overriding the ModuleName() method to get the name from the module …

Run LoadHooks before registering module

---

bootstrap/bootstrap.go

Emit the rules to build blueprint tests even if runGoTests is not
set, and add a phony rule "blueprint_tests" to run them.  This will
allow Soong to stop running the tests at the beginning of every build
but still run them as part of checkbuild or with a manual
`m blueprint_tests`.
Bug: 156428456
Test: m
Test: m blueprint_tests
Change-Id: If293a0757766d3046e78bf230a1825f15adc68fd

Always emit rules for tests and add phony to run them

---

context.go
module_ctx.go
module_ctx_test.go

Adds a CheckBlueprintSyntax(...) method to check the syntax of a
Blueprint file.
Changes processModuleDef and newModule from being method on *Context to
being standalone functions. That ensures that CheckBlueprintSyntax(...)
does not need to take a context and so there is no chance that it can
change its state.

Support checking syntax of generated Blueprint files

---

bootstrap/bootstrap.go
bootstrap/command.go

This reverts commit 63085f9e7c138f15f3edec5e38d7c750a346cfe1.
It breaks the blueprint tests, and we aren't use it yet, so revert
it for now.
Change-Id: I1ac81371342285e8d57baf15fe3a223d4140c6cf

Revert changes that broke the build or tests

---

bootstrap.bash
bootstrap/bootstrap.go
bootstrap/command.go
bootstrap/config.go
live_tracker.go
ninja_defs.go
ninja_writer.go
ninja_writer_test.go

The Android fork of Ninja supports "validations", a node that is
added to the top level of the build graph whenever another node
is in the build graph.  Add support in Blueprint to specify them
on build statements and write them to the ninja.

Add Validations support to Blueprint

---

context.go

Context.ModulePath is a duplicate of Context.BlueprintFile, and is
misleading because it returns the path to the Android.bp, and not
the path to the directory that contains the Android.bp file like
ModuleContext.ModuleDir.
Change-Id: I505136fce3c3d37595cd4b4e08de5e2691a2a0f6

Remove unused Context.ModulePath

---

bootstrap/bpdoc/bpdoc_test.go
bootstrap/bpdoc/properties.go
bootstrap/bpdoc/properties_test.go
bootstrap/bpdoc/reader_test.go

Prior to this change nested properties tagged with `blueprint:"mutated"`
are erroneously included in documentation, this corrects that behavior
and adds testing to verify.

Update bpdocs to filter nested properties by tags

---

context.go
module_ctx.go
module_ctx_test.go
splice_modules_test.go

CreateAliasVariation creates a new variation for the current mutator that is an alias to a variation that was created with CreateVarations by the same mutator.  It is similar to AliasVariation, except that AliasVariation creates an alias from the pre-mutated variant to one of the new variations, while CreateAliasVariation creates an alias from a new post-mutated variation to one of the new variations.
Bug: 164216768
Test: TestCreateAliasVariation

Add CreateAliasVariation

---

bpmodify/bpmodify.go
bpmodify/bpmodify_test.go

aosp/1250007
Add an option "-property", which is an alias to the option "-parameter".
For example if Android.bp contains:
cc_foo {
name: "foo",
}
Then `bpmodify -m foo -a bar -property baz.buz Android.bp` outputs:
cc_foo {
name: "foo",
baz: {
buz: ["bar"],
},
}
Bug: 149715904
Test: go test -v
Change-Id: I9660cff1b5239ccf5aa9ef1a41835b8ac6cd4b9f

bpmodify: handle nested properties

---

bootstrap/bootstrap.go
module_ctx.go

The primary builder may want to create variants of bootstrap modules if they need to fit in to the primary builder's dependency graph.  Enable arbitrary variants of bootstrap modules by only running the module's actions on the primary variant and then copying the result to any other variants that exist.

Enable variants of bootstrap modules

---

context.go
context_test.go
module_ctx.go
module_ctx_test.go
name_interface.go
splice_modules_test.go
visit_test.go

AddFarVariationDependencies was broken by incorrect ordering between aliases and variants, and by an incorrect implementation of the subset function for comparing variationMaps.  This pull request fixes both issues and adds tests.

Fix AddFarVariationDependencies

---

context.go

Pull request #317 made the equality check in moduleMatchingVariant
more correct by comparing the variant maps instead of the names.
Using only the names effectively ignores any variation with an
empty name.  Unfortuantely this broke a current user of
ReplaceDependenciesIf.  Go back to the relaxed check for now.
Test: build on a branch with sdk modules
Change-Id: I11016c8df7bd91fd022d04fd3033756f54d7fa0b

Relax check in moduleMatchingVariant

---

context.go
context_test.go
module_ctx.go

Pass a channel to visitor functions called by parallelVisit that
allows them to pause the current visitor until a given visitor
has finished.  This allows parallelVisit to work on a dependency
graph while it is being mutated.
Test: Test_parallelVisit
Change-Id: Id8b1542c22ac9914439310e31d992ae0d7318d69

Support pausing parallelVisit

---

context.go
module_ctx.go

This is the first part of the change: it adds a shadow method (suffixed
with 'X') for each existing method that adds dependencies. Existing
methods call the corresponding shadow methods and discard return value.
The change does not add runtime overhead on findng dependency modules,
as this has already been done previously.
Test: go test
---
If this approach is ok, further steps will be:
- add similar shadow methods in Soong
- port all Soong code to use the new methods
- remove original (now unused) methods from Soong
- remove original (now unused) methods from Blueprint
- rename methods to get rid of X in Soong
- rename methods to get rid of X in Blueprint
I thought it might be easier to do in many small steps considering how invasive the change is.

Return dependency modules from dependency-adding methods.

---

bootstrap/bpdoc/bpdoc.go

Some anonymous nested properties are missing from property structs,
since setting the property to anonymous is to allow future filtering,
there is no issue if we cannot find the struct.
test: go bpdoc tests
test: m soong_docs

Correct bug in generating anonymous nested props

---

bootstrap/command.go
bootstrap/config.go

This allows exiting bootstrap directly before writing ninja files.
This facilitates shorter runtime on integrations which do processing
which do not require ninja file output.
Test: Manually verified on Soong integration use case which involves
running bootstrap twice in a single program; stopping before ninja
output reduces runtime by ~20s, or ~11%.

Create early-exit hook StopBeforeWriteNinja

---

bootstrap/glob.go

GlobRule uses $out.d for the dep file, it doesn't need an extra
parameter.
Change-Id: Ie753a119c3602c325450909f0240f6eeef9ef243

Remove unnecessary depFile parameter from GlobFile

---

context.go
module_ctx.go
module_ctx_test.go

In particular the formatting of dependencies with variants which lacked
braces that caused them to float together with the dependency names.
Also add some context to the ReplaceDependenciesIf panic message.
Test: m

Improve formatting of some error messages.

---

.github/workflows/build.yml

actions/setup-go@v2.0.3 seems to cause issues with
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Change the precise versions to major versions to get updates.
Also fix the "Install ninja" action to use $GITHUB_PATH.

Fix github builds for deprecated set-env and add-path commands

---

context.go

PreSingletons run after the blueprints have been parsed and can run         
VisitAllModules; however, this seeds the cache of sorted modules which   
may change after mutators have run. This causes recomputation of the        
cache if any deps have been modified since the last time it was run.

Invalidate module group cache if deps are modified

---

bpmodify/bpmodify_test.go
parser/sort.go

bpmodify automatically sorts touched list when it is originally sorted.
Even when a user doesn't want this behavior there's no way to avoid
sorting. For example, lists with version numbers.
Now bpmodify sorts the list only if `-s` is given.
Test: bpmodify_test.go
Change-Id: If2fe9bc871a463a47dd3c0b52982b34c9fde05f0

bpmodify: Do not sort automatically

---

proptools/unpack.go
proptools/unpack_test.go

Values assigned to map properties were silently ignored instead of
reported as an error.  Add a check when recursing into structs that
the value is a map.
Fixes: 177706602
Test: m nothing
Test: TestUnpackErrors

Fix silently ignoring values assigned to map properties

---

pathtools/fs.go
pathtools/glob.go

Glob was calling IsSymlink and IsDir on each visited directory entry,
which resulted in an lstat and then a stat call on each.
Instead, use lstat when not following symlinks and use stat when
following symlinks, then use the result to check if the entry is a
directory.
Change-Id: I83d769e2de64ce8221e952e5204d365aeaf47687

Remove redundant stat/lstat calls from glob

---

glob.go

Callers to glob methods may do in-place modifications on the returned
list of globs, return a copy instead of the cached value.
Test: m nothing && m nothing
Change-Id: Ic9140d1e1900e8724ba0a484f27786e5c15dea90

Return a copy of glob lists

---

bootstrap/command.go
context.go
ninja_defs.go
ninja_strings.go
ninja_writer.go
ninja_writer_test.go
package_ctx.go
scope.go

This stack optimizes Blueprint's ninja writer.  On an internal master branch it reduces the mean soong_build execution time from 91s to 87s (4.4%).

Optimize ninja writer

---

proptools/tag.go
proptools/tag_test.go

The commits optimizes HasTag function by avoiding the call to strings.Split that allocates a list of strings.
Here are some results using gprof to measure the speed improvement of this commit:
**Unoptimized HasTag**
```
ROUTINE ======================== github.com/google/blueprint/proptools.HasTag
80ms      2.47s (flat, cum)  4.47% of Total
.          .     19:   "reflect"
.          .     20:   "strings"
.          .     21:)
.          .     22:
.          .     23:// HasTag returns true if a StructField has a tag in the form `name:"foo,value"`.
40ms       40ms     24:func HasTag(field reflect.StructField, name, value string) bool {
20ms      430ms     25:   tag := field.Tag.Get(name)
10ms      1.98s     26:   for _, entry := range strings.Split(tag, ",") {
.       10ms     27: …
```

Optimize HasTag function
